languageCode = "cn-zh"
title = "Onqee"
paginate = 10
uglyURLs = true
enableRobotsTXT = true
hasCJKLanguage = true

[menu]
  [[menu.main]]
    identifier = "dev"
    name = "编程"
    title = "程序开发"
    url = "/dev.html"
    weight = 0
  [[menu.main]]
    identifier = "notes"
    name = "日志"
    title = "我的个人日志"
    url = "/notes.html"
    weight = 0

[taxonomies]
  tag = "tags"

[author]
  name = "onqee"

[params]
  description = "onqee site"
